# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = opacity 0.92, match:class .*
windowrule = opacity 0.94, match:class (com\.mitchellh\.ghostty)
windowrule = opacity 0.94, match:class (firefox)
windowrule = opacity 1, match:class (Brave-browser)
windowrule = opacity 1, match:class (.*factorio.*)
windowrule = opacity 1, match:class (steam_app_.*)
windowrule = opacity 1, match:class (.*Nomifactory.*)
windowrule = opacity 1, match:class (.*Minecraft.*)
windowrule = opacity 1, match:class (.*Project Zomboid.*)
windowrule = opacity 1, match:class (.*zoom.*)
windowrule = opacity 0.1, match:class (.*Annotation.*)
windowrule = opacity 0.6, match:title cava

windowrule = float 1, match:class (thunderbird), match:initial_title ^(.*)(Reminder)(.*)$
windowrule = pseudo 1, match:class (thunderbird), match:initial_title ^(.*)(Reminder)(.*)$
windowrule = float 1, match:class (thunderbird), match:initial_title ^(.*)(An error has occured)(.*)$
windowrule = pseudo 1, match:class (thunderbird), match:initial_title ^(.*)(An error has occured)(.*)$

windowrule = no_blur 1, pseudo float, match:class (steam_app_.*)
windowrule = no_blur 1, pseudo float, match:class (Steam.*)
