console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
debug = true

# [palette]
#   black = '#262B44'
#   blue = '#4B95E9'
#   green = '#59C9A5'
#   orange = '#F07623'
#   red = '#D81E5B'
#   white = '#E0DEF4'
#   yellow = '#F3AE35'

[secondary_prompt]
  template = ' ⟩⟩ '
  foreground = 'foreground'
  background = 'transparent'

[transient_prompt]
  template = ' ⟩ '
  foreground = 'foreground'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'background'
  background = 'yellow'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'white'
  background = 'blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true

[cache]
duration = "1h"
strategy = "folder"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    foreground = 'black'
    background = 'yellow'
    type = 'os'
    style = 'diamond'
    template = " {{ if .WSL }}WSL at {{ end }}{{ .Icon }} "

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'black'
    background = 'yellow'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ if not .Writable }} {{ else }} {{ end }} {{ .Path }} '
    foreground = 'white'
    powerline_symbol = ''
    background = 'red'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'black'
    powerline_symbol = ''
    background = 'green'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}white{{ end }}', '{{ if gt .Ahead 0 }}white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  '
    foreground = 'white'
    powerline_symbol = ''
    background = 'yellow'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'white'
    background = 'blue'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false
      cache_duration = '4h'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '
    foreground = 'yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = true
      cache_duration = '4h'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'foreground'
    background = 'transparent'
    template = ' ⏱  took <blue><b>{{ .FormattedMs }}</b></> '

  [[blocks.segments]]
    template = 'at <blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' ⟩'

  
